"""
Dynamically creates an instance of class 'User' based on variables from user_data file
Input:
    - path to user data file
    - name for the class
    
code generated by chatgpt
"""
class DynamicClass:
    """Helper class for user initiation.
    """
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)

def create_class_from_file(file_path, class_name):
    """Create user class.

    Parameters
    ----------
    file_path : path 
        Path to user_data file.
    class_name : string
        Define class name.

    Returns
    -------
    Class
        User class
    """
    variables = {}
    with open(file_path, "r") as file:
        code = compile(file.read(), file_path, "exec")
        exec(code, variables)
    
    CustomClass = type(class_name, (DynamicClass,), variables)
    return CustomClass()

def create_user():
    """Dynamically creates user with data from 'user_data.py' file.

    Returns
    -------
    Class
        User class
    """
    return create_class_from_file('./user_data.py', 'User')
