[tool.poetry]
name = "smit"
version = "0.2.0"
description = "Scrape and plot energy usage data."
authors = ["Christian Koplenig <tmpck@gmx.net>"]
license = "MIT"
readme = "README.md"

packages = [
    {include = "SMIT", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
customtkinter = "5.2.1"
matplotlib = "3.8.0"
pandas = "2.1.3"
rsa = "4.9"
seaborn = "0.13.0"
selenium = "4.15.2"
tomlkit = "0.12.3"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.2"
tox = "^4.11.3"
tox-poetry-installer = "1.0.0b1"

[tool.pytest.ini_options]
markers = [ 
    "smoke: Validate all core methods",
    "application: Test setup of application class",
    "crypto: Test rsa implementation",
    "osinterface: Move files, generate pandas dataframe",
    "persistence: Check dates variable",
    "scraping: Webdriver setup",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
