# Login credentials
login_url = 'https://webportal.stromnetz-graz.at/login'
username = 'email'

# Stromnetz Anlagedaten
day_meter   = '000000'  # Zaehlpunktnummer Tagstrom; last six numbers
night_meter = '000001'  # Zaehlpunktnummer Nachtstrom; last six numbers