[Login]
url = 'https://webportal.stromnetz-graz.at/login'
username = 'ch.koplenig@posteo.net'
password = "Worz6YxmsJ6N6vnJGN1r+g8LvHLyrOGC+/H4ATu2iJ6y8Fx3QDekvOEpem85q2PVUJ+qyfCrTogsVMGYYBV62MmpK4+llHa877eK8X6sc287RW9Loi3VPCxrOnx/eCFfLTAjmwTjtNa2/wtr5eVsIBTlZq1a8WJISio8vbUSlzY=" # Permission to store password given

[Meter]
# Stromnetz Anlagedaten
day_meter   = '199996'  # Zaehlpunktnummer Tagstrom; last six numbers
night_meter = '199997'  # Zaehlpunktnummer Nachtstrom; last six numbers