[Login]
url = 'https://webportal.stromnetz-graz.at/login'
username = ''

[Meter]
# Stromnetz Anlagedaten
day_meter   = '' # Zaehlpunktnummer Tagstrom; last six numbers
night_meter = '' # Zaehlpunktnummer Nachtstrom; last six numbers